name: angular2_google_signin
description: Angular2 google sign-in component.
version: 0.1.0+2
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/angular2_google_signin

environment:
  sdk: '>=1.13.1 <2.0.0'

dependencies:
  angular2: ^2.0.0-beta.10
  js: ^0.6.0

transformers:
- angular2